# Project identification
sonar.projectKey=lotacao-maxima-sala-espera-frontend
sonar.projectName=lotacao-maxima-sala-espera-frontend
sonar.host.url=${env.SONAR_HOST_URL}
sonar.token=${env.SONAR_TOKEN}

# Scan setup
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.spec.ts

# Test setup
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Coverage report path (ensure coverage is generated first)
sonar.javascript.lcov.reportPaths=coverage/lotacao-sala-espera-web/lcov.info
