spring:
  application:
    name: lotacao-maxima-sala-espera
  web:
    locale: pt_BR

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi.yaml
    disable-swagger-default-url: true
    operationsSorter: method
    tagsSorter: alpha
